# Generated by Django 6.0.6 on 2026-09-09 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Singular name, e.g. Pharmacy', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Plural/display label, e.g. Pharmacies', max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated search aliases', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Healthcare Provider Category',
                'verbose_name_plural': 'Healthcare Provider Categories',
                'db_table': 'provider_categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order', 'name'], name='provider_ca_is_acti_42f5fd_idx'), models.Index(fields=['is_featured', 'sort_order'], name='provider_ca_is_feat_f5904d_idx')],
            },
        ),
    ]
