# Generated by Django 6.0.6 on 2026-09-09 01:49

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='providers/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('alternate_numbers', models.JSONField(blank=True, default=list)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('locality', models.CharField(blank=True, db_index=True, max_length=120)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Provider location as longitude/latitude point', null=True, srid=4326)),
                ('offerings', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='providers', to='providers.providercategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='locations.city')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
                'ordering': ['-is_featured', 'name'],
                'indexes': [models.Index(fields=['is_active', 'city'], name='providers_is_acti_25b5d3_idx'), models.Index(fields=['is_active', 'locality'], name='providers_is_acti_28e35d_idx'), models.Index(fields=['is_verified', 'is_active'], name='providers_is_veri_0d2c3b_idx'), models.Index(fields=['is_featured', 'is_active'], name='providers_is_feat_7939ef_idx')],
            },
        ),
    ]
