# Generated by Django 6.0.6 on 2026-09-09 07:49

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import providers.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderHour',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), help_text='Weekdays sharing this slot (Monday=0, Sunday=6).', size=7, validators=[providers.validators.validate_provider_days])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_hours', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_hours',
                'ordering': ('provider_id', 'opens_at', 'id'),
                'indexes': [models.Index(fields=['provider', 'opens_at'], name='provider_hours_open_idx'), django.contrib.postgres.indexes.GinIndex(fields=['days'], name='provider_hours_days_gin')],
                'constraints': [models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='provider_hour_closes_after_open'), models.UniqueConstraint(fields=('provider', 'days', 'opens_at', 'closes_at'), name='provider_hour_slot_unique')],
            },
        ),
    ]
