# Generated by Django 6.0.6 on 2026-09-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provider_owner_and_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='provider',
            new_name='providers_owner_i_465557_idx',
            old_name='providers_owner__4ee99d_idx',
        ),
    ]
