# Generated by Django 6.0.6 on 2026-09-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_rename_providers_owner__4ee99d_idx_providers_owner_i_465557_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_medicine_enquiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_test_book',
            field=models.BooleanField(default=False),
        ),
    ]
