# Generated by Django 6.0.6 on 2026-08-29 06:17

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a two-letter uppercase state code.', regex='^[A-Z]{2}$')])),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='locations_s_name_5adbc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4')], default=2)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='locations.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('aliases', models.CharField(blank=True, default='', help_text='Comma-separated alternate names/search terms.', max_length=300)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Representative point (longitude, latitude).', null=True, srid=4326)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='locations.city')),
            ],
            options={
                'verbose_name_plural': 'Localities',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['city', 'name'], name='locations_l_city_id_e5afb3_idx'), models.Index(fields=['city', 'slug'], name='locations_l_city_id_070be2_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'slug'), name='unique_locality_slug_per_city')],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'name'], name='locations_c_state_i_eef7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'slug'], name='locations_c_state_i_5cc03d_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['tier'], name='locations_c_tier_d49330_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'slug'), name='unique_city_slug_per_state'),
        ),
    ]
