# Generated by Django 6.0.6 on 2026-09-09 09:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('providers', '0003_providerhour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('registration_council', models.CharField(blank=True, max_length=150)),
                ('registration_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('consultation_type', models.CharField(choices=[('walk_in', 'Walk-in'), ('appointment', 'Appointment')], default='walk_in', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='male', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('bio', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list, help_text="Example: ['English', 'Hindi', 'Bengali']")),
                ('treatments', models.JSONField(blank=True, default=list, help_text='Treatments/services commonly provided by the doctor.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='providers.provider')),
                ('specialties', models.ManyToManyField(blank=True, related_name='doctors', to='doctors.doctorspecialty')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
                'ordering': ['-is_featured', 'name'],
                'indexes': [models.Index(fields=['is_active', 'provider'], name='doctors_is_acti_800f3e_idx'), models.Index(fields=['is_featured', 'is_active'], name='doctors_is_feat_0045f8_idx')],
            },
        ),
    ]
