# Generated by Django 6.0.6 on 2026-09-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_type',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='consultation_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('appointment', 'Appointment')], db_index=True, default='walk_in', max_length=30),
        ),
    ]
