# Generated by Codex on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_remove_doctor_consultation_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="doctorschedule",
            name="doctor_schedule_end_after_start",
        ),
        migrations.AlterField(
            model_name="doctorschedule",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctorschedule",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="doctorschedule",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(start_time__isnull=True, end_time__isnull=True)
                    | models.Q(end_time__gt=models.F("start_time"))
                ),
                name="doctor_schedule_end_after_start",
            ),
        ),
    ]
